### ISSUE TITLE
UI: layout changes when answers are revealed

### ISSUE THREAD

**Issue by derivator** [joshzcold/Cold-Family-Feud#18]
Revealing an answer resizes the column that it's in, would be cool if that didn't happen. Maybe the boxes could be fixed and the text could change size to fit?

**Comment by joshzcold** [comment]
Example: 
![ColdFeudUIProblem](https://user-images.githubusercontent.com/36175703/113580313-c5e1f700-95e2-11eb-8766-081ed9041136.gif)

**Comment by joshzcold** [comment]
Covered by https://github.com/joshzcold/Cold-Family-Feud/pull/23
