### ISSUE TITLE
Feature Request: View/Kick registered players from admin console

### ISSUE THREAD

**Issue by Neillbar** [joshzcold/Cold-Family-Feud#24]
Hi, i deployed this to my own server but i can't refresh all the names. i will look into the code and see if i can add code to clear it but i am not a react developer, so ill check. 

But i would like to request a feature to show all the players in dash where you can just delete them so you dont have duplicates. or if player looses connection it removes them automatically and they must just sign in again

**Comment by joshzcold** [comment]
Hey Neillbar. 
>but i can't refresh all the names.

I assume your talking about when players join they can't quit or restart unless you start the application over

I am currently working on a "room code" feature where players can host or join a room and quit the game if needed.

check out branch `room_codes` and see if it covers what your looking for. The functionality should be there, but im tweaking the visuals now. 

When the host quits the game then all players are disconnected. 

The ability to see and kick registered players would be a good addition.

Im not a web developer professionally so mind my 🍝 😀 while you check out the code.

**Comment by Neillbar** [comment]
Thanks for the quick response, wish i could help if it was flutter or angular i could've helped! 

Yeah the room code feature is awesome, just tested it out but for some reason my game section does not work, it just shows loading... forever no error

**Comment by joshzcold** [comment]
launch the game with the admin console. Theres a new button. Uses a cookie to join into the game.

**Comment by Neillbar** [comment]
i don't see the launch button ? i am able to register players etc.. but game board just shows loading

**Comment by joshzcold** [comment]
ahh then thats an issue. let me check.

**Comment by Neillbar** [comment]
it looks like the game.teams is null, that is why it shows the loading... screen.

**Comment by joshzcold** [comment]
yeah, I thought I already coded in the functionality, but I guess not. 
Now you can try a git pull and the game window should come up.

One thing that is definitely true is that this feature needs tons of testing.
Probably will have to start automated testing considering all the small things that could break.

**Comment by Neillbar** [comment]
yeah sure, man i can also help out with testing and let you know etc.. 

another thing none of the sounds are working on my side, only the theme song that you can play through dash. i saw something in your readme file about the sound ill see if i go play around in the settings.

**Comment by Neillbar** [comment]
Just checked something, is the buzzer sound suppose to work ? like on the game board and/or on the users page ?

**Comment by joshzcold** [comment]
no buzzer sound coded in. Might be overwhelming with a lot of players

**Comment by Neillbar** [comment]
> no buzzer sound coded in. Might be overwhelming with a lot of players
> 
> Edit: wouldn't mind a sound playing on the players buzzer screen when they click it. Might be kinda fun if your contestants are all playing in the same family room to "hear" which player got it first
> 
> ill make a feature request for that.

Yeah i understand, you can maybe do something to only do buzzer once (for the first person that pressed it) anything after it does not make a sound. until all buzzers are cleared.

**Comment by joshzcold** [comment]
Covered by https://github.com/joshzcold/Cold-Family-Feud/pull/30
