### ISSUE TITLE
Stuck on "Loading..."

### ISSUE THREAD

**Issue by derivator** [joshzcold/Cold-Family-Feud#27]
I just tried the latest commit and the Game and Admin pages both get stuck on "Loading..."

**Comment by joshzcold** [comment]
Check out this message thread. 
https://github.com/joshzcold/Cold-Family-Feud/issues/24
Basically branch `room_codes` should have enough functionality to use. 

Ill try branch `master` and check the problem. Might be worth it to try a tagged release if I broke master.

**Comment by joshzcold** [comment]
Seems to be working for me 
![Peek 2021-06-05 10-59](https://user-images.githubusercontent.com/36175703/120899542-76717480-c5ed-11eb-969e-0e2bc3d2e160.gif)
Got a list of steps to take to make the game data invalid?
Server output?

**Comment by derivator** [comment]
I think it might be a dependency issue with npm... Clean checkout into a new directory fixed it. After `npm install react-i18next` it builds and runs normally. In my old working directory I get
```
$ npm run start

> cold_family_feud@1.1.0 start
> NODE_ENV=production node server.js

info  - Using webpack 5. Reason: no next.config.js https://nextjs.org/docs/messages/webpack5
> Ready on http://localhost:3000
```
where that line about webpack is the only one that differs from the output of the working version.
No further steps needed, game is broken from the get go.

I assume that I'm missing some Node knowledge here, perhaps you could include instructions for how to get the dependencies sorted out in the readme?

**Comment by joshzcold** [comment]
`react-i18next` is located in package.json 
```
    "react-dom": "^17.0.1",
    "react-i18next": "^11.8.13",
    "react-router-dom": "^5.2.0",
```
Any time I add a new dependency you gotta run `npm install` to get it. 

im guess you got "loading..." because the server couldn't import i18next and just ran into an error.

**Comment by joshzcold** [comment]
Im thinking there could be a better way to package up the app. Might be a good reason to package it up in docker or electron.

**Comment by derivator** [comment]
Just to clarify, I had installed react-i18next in my previous working directory (where the problem occurred) as well, my guess is something failed to get updated or some leftover config file screwed everything up. I was just wondering if there's a better way than starting over with a clean working directory...

**Comment by joshzcold** [comment]
removing `node_modules` and doing `npm install` should be enough.

**Comment by joshzcold** [comment]
Im going to go ahead and close this since its not a code issue. 
I added the "Update via git" helper snippet in the readme.
