### ISSUE TITLE
Bug: error messages coming from server should be translated. i18n

### ISSUE THREAD

**Issue by joshzcold** [joshzcold/Cold-Family-Feud#28]

**Comment by joshzcold** [comment]
![image](https://user-images.githubusercontent.com/36175703/120899306-4a092880-c5ec-11eb-9169-26327e791218.png)
Example of message coming from server.

**Comment by eddiep12** [comment]
I would like to contribute. Where can I find the code for this bug?

**Comment by joshzcold** [comment]
Hey @eddiep12 
https://github.com/joshzcold/Cold-Family-Feud/blob/master/pages%2Fapi%2Fws.js#L541

This file is pretty much all the backend logic.

Any return to the websocket action "error" would be this bug/feature

The "error" action gets returned and the client side immediately shows it either in the console.log or in the UI

You either have to trigger the translation function here or in all places in the frontend.

Thanks for your consideration in contributing ❤️

Good luck 👍
