### ISSUE TITLE
Show final round(s) total before the 1st rounds answers are revealed.

### ISSUE THREAD

**Issue by JBaczuk** [joshzcold/Cold-Family-Feud#48]
Family played this last night, i was really fun, nice job again! I've taken some notes of things I will try to submit for a PR, because I can see us using it again. I wasn't sure how to finish the game, though, after the money round. It seems there wasn't a way to total up the points and determine if they won the bonus round, but I assume that may not have been added yet...

**Comment by joshzcold** [comment]
So its not the best interface to determine a win. 
![image](https://user-images.githubusercontent.com/36175703/146795980-1050af6a-9594-4d1d-aa13-d688532fb13e.png)
hardcoded to 200
 (which I believe is what the show determines is a win?) 
 https://user-images.githubusercontent.com/36175703/146796224-68233024-263e-4f75-97e7-7b5b614be3ce.mp4

im thinking the confusion came from the fact that the total doesn't reveal itself until you click the "Reveal First Round Answers" Button at which point the 1 & 2 rounds of fast money totals get added up.

Does the show happen to show the first round total while the second contestant is up? I think that makes more sense then hiding everything.

**Comment by joshzcold** [comment]
@JBaczuk  im updating this issue's title to reflect what I think made the confusion.

**Comment by joshzcold** [comment]
Fixed in https://github.com/joshzcold/Cold-Family-Feud/pull/51
please reopen if you need to. 
thanks 👍

**Comment by joshzcold** [comment]
deployed to https://famf.app 
![image](https://user-images.githubusercontent.com/36175703/147301325-a5f45a34-6e3f-406f-8b91-f28a307154a5.png)

**Comment by JBaczuk** [comment]
@joshzcold Sounds good! I think it's great that you can basically navigate to any point within the game, it's just not clear what the "next" step is at any point. I wonder if highlighting the button that should be clicked next would help...

**Comment by joshzcold** [comment]
I've been trying thinking about how to teach people to use the admin console. Like if a school teacher wanted to use it or something. 

I know some websites use an interactive tutorial, but maybe that's overkill. 

Either way highlighting the buttons is a good idea as well.
