### ISSUE TITLE
Featured Request : Additional language

### ISSUE THREAD

**Issue by PitaLife** [joshzcold/Cold-Family-Feud#49]
Can you add Indonesian in your game

**Comment by joshzcold** [comment]
If you can double check the resulting language file for accuracy I'll get started on 

Running the English translation.json file automatically through Google translate.

I'll give you a link to the pull request when it's ready.

**Comment by joshzcold** [comment]
@PitaLife  please check out the pull request here https://github.com/joshzcold/Cold-Family-Feud/pull/50

If I can ask a favor can you:
1. try out the functionality of that branch.
2. review the grammar of the translated values at https://github.com/joshzcold/Cold-Family-Feud/blob/1492aef1537355eae1f208fd2c2ad70c190b9143/public/locales/id/translation.json

thank you 👍
