### ISSUE TITLE
How to edit title text?

### ISSUE THREAD

**Issue by Simplegram** [joshzcold/Cold-Family-Feud#55]
I want to change the title from Family Feud to Super Family 100.

**Comment by joshzcold** [comment]
Currently you can only change the first word.
Something like
`Family Feud` -> `Johnson's Family Feud`

Didn't realize people would want to change the whole title.

**Comment by joshzcold** [comment]
If you want this change for a game your hosting sometime soon I would go just manually edit 

https://github.com/joshzcold/Cold-Family-Feud/blob/ef55f473f4d4041926312569cdc1bf67e471f675/components/title-logo.js#L238

Then refresh/rebuild

**Comment by Simplegram** [comment]
Thank you for your reply.

I managed to change the whole title and other few things by editing the English translation json file. Changing every "family" and "feud" also worked. I also managed to customize the UI a bit by editing the return CSS. Everything else is working wonderfully after that :)

Thank you for this awesome project!
