### ISSUE TITLE
Debian Bookworm openssl-legacy-provider error

### ISSUE THREAD

**Issue by vibrantlee** [joshzcold/Cold-Family-Feud#67]
When starting the app with npm run build, I get an error from the NODE_OPTIONS:

> cold_family_feud@1.1.0 build
> NODE_OPTIONS=--openssl-legacy-provider next build

sh: 1: next: not found

Any ideas? Thank you!

**Comment by joshzcold** [comment]
Have you tried `npm install` first?

**Comment by mradzwilla** [comment]
@vibrantlee  If you haven't figured it out yet, I was able to get it up and running by running `npm install --save-dev` and removing the references to `NODE_OPTIONS=--openssl-legacy-provider` from package.json

**Comment by joshzcold** [comment]
Closing this is a nodejs versioning issue.
You can use https://github.com/nvm-sh/nvm so you can switch between versions as your building this.

`nvm install`
`nvm use`

or `nvm install 18`
`nvm use`
