### ISSUE TITLE
Bug: Final Round Timer stuck on "Stop Timer" in admin

### ISSUE THREAD

**Issue by theredwillow** [joshzcold/Cold-Family-Feud#71]
When start_timer is kicked off in game.js, an interval is started. When the interval's limit (which also acts as an iterator index) hits zero, the interval is cleared. However, the admin page never receives this information. A message needs to be sent back through the socket so that the admin's button can be reset to the "Start Timer" state.

**Comment by joshzcold** [comment]
Confirmed issue. Easy fix.
