### ISSUE TITLE
JSON's are cluttered by state data

### ISSUE THREAD

**Issue by theredwillow** [joshzcold/Cold-Family-Feud#73]
The games folder's JSON files are filled with unnecessary game state such as "selection" and "input". These things can be added when the state is initialized and greatly alleviate the readability of the library data.

**Comment by joshzcold** [comment]
Yes it would be nice to remove the state data.
We need to make sure that old created games when loaded don't conflict with new logic to add the state data.
which shouldn't be a problem.

**Comment by theredwillow** [comment]
Making the initialized state data be optionally provided fields in the JSON seems like the way to approach that. Old versions would work, new versions would work, and people who want to preselect the answer for whatever reason can do that too.

**Comment by joshzcold** [comment]
Closed by https://github.com/joshzcold/Cold-Family-Feud/pull/80
