### ISSUE TITLE
Bug: Cached logo

### ISSUE THREAD

**Issue by theredwillow** [joshzcold/Cold-Family-Feud#75]
If the host adds a logo image but then removes it and adds a different one, the buzzers/users will not update the image. I believe this is because the browsers cache the URL.

**Comment by joshzcold** [comment]
Confirmed issue. Users currently have to refresh the browser to get the new image.

**Comment by karlromets** [comment]
I've attempted to reproduce, my image updates. @joshzcold has this issue been fixed? If not could you please share steps to reproduce? Would like to take a look.

**Comment by joshzcold** [comment]
Hey @karlromets thanks for taking a look.

It happens when you trying to change images by

1. Uploading a logo image
2. Clicking to reset the image 
3. Upload a new image

Check the game page and you will see the first image.

**Comment by karlromets** [comment]
Okay got it to occur, before I was actually uploading .jpg and then a .gif, which meant that the files were cached but changed on the screen due to different URLs due to different file types.

**Comment by joshzcold** [comment]
Ahh great find!
Thank you for the PR

**Comment by joshzcold** [comment]
deployed to famf.app
