### ISSUE TITLE
feature request: undo

### ISSUE THREAD

**Issue by alxyang** [joshzcold/Cold-Family-Feud#81]
it seems that as the host if i accidentally misclick and e.g. award the incorrect team points, there is no way to undo this. supporting an undo function would be useful in certain scenarios. I think this could be done by maintaining a stack of last actions that occurred in game state?

**Comment by joshzcold** [comment]
Certainly possible. My method around this was to allow the admin to edit the points directly, but that would require memory of the previous point values.

**Comment by joshzcold** [comment]
What if "award points" was a toggle button that also subtracted? Would that solve this scenario?

**Comment by joshzcold** [comment]
I believe the ability to "unclick" an answer and also manually adjust points to the teams covers the need for an undo feature.
I thinking keeping the state of a the game in a list might balloon the memory per each game (in my opinion)
