### ISSUE TITLE
Origin is unreachable Error code 523 / Host Error www.famf.app

### ISSUE THREAD

**Issue by yourbelovedtito** [joshzcold/Cold-Family-Feud#83]
Host error on www.famf.app

Origin is unreachable Error code 523

![Origin Issue](https://github.com/joshzcold/Cold-Family-Feud/assets/165944884/7f610477-2f89-486d-a421-0ddf386b86d8)

**Comment by joshzcold** [comment]
My home server was down cause I tripped on the power cord, lol.

Thanks for your report
