### ISSUE TITLE
Open game window on another computer

### ISSUE THREAD

**Issue by ngbrown** [joshzcold/Cold-Family-Feud#86]
Instead of needing to use a computer with two monitors, one hooked up to the shared screen, it would be nice if the game window could join a session and be hosted from a separate computer.

I would use that to connect on one of the devices with a browser attached to a TV like an XBox, Playstation, Firestick, or Chromecast device.

The code could be the same as the main game, or one generated and shown only on the host screen.

**Comment by joshzcold** [comment]
Got started on a branch https://github.com/joshzcold/Cold-Family-Feud/tree/game_window_on_buzzer https://github.com/joshzcold/Cold-Family-Feud/compare/master...game_window_on_buzzer

Im pretty close to finishing the feature. There is just some css that is missing. 

Had to add a "Exit" button on the game window for the user joining in as a spectator and it need to meld well with the rest of the game window UI.

**Comment by joshzcold** [comment]
Closed by https://github.com/joshzcold/Cold-Family-Feud/pull/88
