### ISSUE TITLE
Cant add custom via json.

### ISSUE THREAD

**Issue by NoahTheBaguette** [joshzcold/Cold-Family-Feud#91]
I'm trying to upload my json file to the site but it does nothing when I click submit.

`{
  "rounds": [
    {
      "answers": [
        {
          "ans": "Menorah",
          "pnt": 45
        },
        {
          "ans": "Dreidel",
          "pnt": 35
        },
        {
          "ans": "Latkes",
          "pnt": 10
        },
        {
          "ans": "Sufganiyot",
          "pnt": 7
        }
      ],
      "multiply": 1,
      "question": "Name Something Associated with Hanukkah."
    },
    {
      "answers": [
        {
          "ans": "Maccabees",
          "pnt": 52
        },
        {
          "ans": "Judah",
          "pnt": 26
        },
        {
          "ans": "Oil",
          "pnt": 12
        },
        {
          "ans": "Temple",
          "pnt": 5
        }
      ],
      "multiply": 1,
      "question": "Name A Key Element in the Hanukkah Story."
    },
    {
      "answers": [
        {
          "ans": "Gelt",
          "pnt": 40
        },
        {
          "ans": "Gold Coins",
          "pnt": 28
        },
        {
          "ans": "Chocolate Coins",
          "pnt": 16
        },
        {
          "ans": "Candy",
          "pnt": 8
        }
      ],
      "multiply": 1,
      "question": "Name A Type of Hanukkah Gift Often Given to Children."
    },
    {
      "answers": [
        {
          "ans": "Blue",
          "pnt": 50
        },
        {
          "ans": "White",
          "pnt": 32
        },
        {
          "ans": "Silver",
          "pnt": 10
        },
        {
          "ans": "Gold",
          "pnt": 5
        }
      ],
      "multiply": 2,
      "question": "Name A Color That is Commonly Seen During Hanukkah Decorations."
    },
    {
      "answers": [
        {
          "ans": "Eight",
          "pnt": 63
        },
        {
          "ans": "Nine",
          "pnt": 23
        },
        {
          "ans": "Seven",
          "pnt": 9
        },
        {
          "ans": "Ten",
          "pnt": 5
        }
      ],
      "multiply": 2,
      "question": "How Many Nights Does Hanukkah Last?"
    },
    {
      "answers": [
        {
          "ans": "Candles",
          "pnt": 45
        },
        {
          "ans": "Lights",
          "pnt": 28
        },
        {
          "ans": "Menorah",
          "pnt": 16
        },
        {
          "ans": "Shamash",
          "pnt": 11
        }
      ],
      "multiply": 2,
      "question": "Name Something You Light During Hanukkah."
    }
  ],
  "final_round": [
    {
      "answers": [
        [
          "Latkes",
          48
        ],
        [
          "Sufganiyot",
          26
        ],
        [
          "Dreidel",
          14
        ],
        [
          "Candles",
          8
        ],
        [
          "Menorah",
          4
        ]
      ],
      "question": "Name Something People Eat During Hanukkah."
    },
    {
      "answers": [
        [
          "Judah",
          52
        ],
        [
          "Maccabees",
          28
        ],
        [
          "Temple",
          14
        ],
        [
          "Hanukkah Miracle",
          6
        ]
      ],
      "question": "Name a Famous Figure from the Hanukkah Story."
    },
    {
      "answers": [
        [
          "Dreidel",
          65
        ],
        [
          "Menorah",
          23
        ],
        [
          "Latkes",
          8
        ],
        [
          "Gelt",
          4
        ]
      ],
      "question": "Name a Popular Hanukkah Game."
    },
    {
      "answers": [
        [
          "Blue",
          50
        ],
        [
          "Silver",
          32
        ],
        [
          "White",
          12
        ],
        [
          "Gold",
          6
        ]
      ],
      "question": "Name a Common Color Seen in Hanukkah Decorations."
    }
  ],
  "final_round_timers": [
    20,
    25
  ]
}
`

**Comment by joshzcold** [comment]
Hey @NoahTheBaguette your game is working for me. 

How are you "submitting" the game? I have a feeling you might be on the https://www.famf.app/new page which is only meant for creating new games and "submit" on that page just means fill in the fields of the "Create New Game Page"

Once you download your json file you are supposed to go back to the admin page and click on the upload button icon
![image](https://github.com/user-attachments/assets/854b4b21-f8af-447a-b261-7c28c716f2c5)

Which is in the box next to the built-in game selector
![image](https://github.com/user-attachments/assets/6328eb59-2a86-4fb9-a878-4606ea2ff5a8)

I will admit that the UI on the new game page does "convey" better that you are uploading your custom game more than the admin page, so I believe there could be a change in UX.

If you are using the admin controls (instead of the new game control) and it still doesn't work, then maybe this is browser, os specific and you can send me some screenshots or specs of your machine?

**Comment by NoahTheBaguette** [comment]
Sure thing I’ll get right on it as soon as I get a chance

**Comment by NoahTheBaguette** [comment]
I just tried with a one I found on GitHub and it worked but my original file was a custom one. can you look through and see what is wrong?

`{ "rounds": [ { "answers": [ { "ans": "Menorah", "pnt": 45 }, { "ans": "Dreidel", "pnt": 35 }, { "ans": "Latkes", "pnt": 10 }, { "ans": "Sufganiyot", "pnt": 7 } ], "multiply": 1, "question": "Name Something Associated with Hanukkah." }, { "answers": [ { "ans": "Maccabees", "pnt": 52 }, { "ans": "Judah", "pnt": 26 }, { "ans": "Oil", "pnt": 12 }, { "ans": "Temple", "pnt": 5 } ], "multiply": 1, "question": "Name A Key Element in the Hanukkah Story." }, { "answers": [ { "ans": "Gelt", "pnt": 40 }, { "ans": "Gold Coins", "pnt": 28 }, { "ans": "Chocolate Coins", "pnt": 16 }, { "ans": "Candy", "pnt": 8 } ], "multiply": 1, "question": "Name A Type of Hanukkah Gift Often Given to Children." }, { "answers": [ { "ans": "Blue", "pnt": 50 }, { "ans": "White", "pnt": 32 }, { "ans": "Silver", "pnt": 10 }, { "ans": "Gold", "pnt": 5 } ], "multiply": 2, "question": "Name A Color That is Commonly Seen During Hanukkah Decorations." }, { "answers": [ { "ans": "Eight", "pnt": 63 }, { "ans": "Nine", "pnt": 23 }, { "ans": "Seven", "pnt": 9 }, { "ans": "Ten", "pnt": 5 } ], "multiply": 2, "question": "How Many Nights Does Hanukkah Last?" }, { "answers": [ { "ans": "Candles", "pnt": 45 }, { "ans": "Lights", "pnt": 28 }, { "ans": "Menorah", "pnt": 16 }, { "ans": "Shamash", "pnt": 11 } ], "multiply": 2, "question": "Name Something You Light During Hanukkah." } ], "final_round": [ { "answers": [ [ "Latkes", 48 ], [ "Sufganiyot", 26 ], [ "Dreidel", 14 ], [ "Candles", 8 ], [ "Menorah", 4 ] ], "question": "Name Something People Eat During Hanukkah." }, { "answers": [ [ "Judah", 52 ], [ "Maccabees", 28 ], [ "Temple", 14 ], [ "Hanukkah Miracle", 6 ] ], "question": "Name a Famous Figure from the Hanukkah Story." }, { "answers": [ [ "Dreidel", 65 ], [ "Menorah", 23 ], [ "Latkes", 8 ], [ "Gelt", 4 ] ], "question": "Name a Popular Hanukkah Game." }, { "answers": [ [ "Blue", 50 ], [ "Silver", 32 ], [ "White", 12 ], [ "Gold", 6 ] ], "question": "Name a Common Color Seen in Hanukkah Decorations." } ], "final_round_timers": [ 20, 25 ] } `

**Comment by joshzcold** [comment]
Do you have a screenshot of what happens when you try to upload the json file?

I do have a MacBook myself, so I can give it a try

The CSV error is because the game is larger than like 15 rows of data.

**Comment by joshzcold** [comment]
Your game is definitely in the right format and loads up fine for me, so we need to figure out what the actual issue is.

Anything in the browser console logs?

**Comment by joshzcold** [comment]
Just tried it on my M2 apple air, so that isnt' the issue.

What browser are you using?

**Comment by joshzcold** [comment]
Maybe also upload the file to a comment as well?
Its perhaps the format of the file on your machine has something the Json parser doesn't like.

Something like line endings could be the issue.

**Comment by joshzcold** [comment]
@NoahTheBaguette any update? Would love to get your game working before Hanukkah 😉

**Comment by ItzEarthy** [comment]
I am also experiencing this issue. I am using Windows and Chrome. When I try to add a custom game on the host page, nothing happens. However, when I do the same on the create game page, it shows up but the create button doesn't work.
[ChristmasGame#1.json](https://github.com/user-attachments/files/18189281/ChristmasGame.1.json)

**Comment by joshzcold** [comment]
@ItzEarthy any browser console logs to indicate what the problem is?

I'll try your game but I bet it's going to work on my setup like @NoahTheBaguette 's game did

**Comment by NoahTheBaguette** [comment]
I found the solution to the problem. For me there was an issue with my JPEG file because I was converting it from CSV to JPEG and it had issues the way I fixed it was by going to the games folder and downloading one of the json files. I then was able to upload that just on the admin page not the new page. And all I had to do to resolve that issue was edit the json I downloaded and it worked.

**Comment by NoahTheBaguette** [comment]
Thank you so much @joshzcold for making the game and assisting me. It was very kind of you to try to get it working before Hanukkah.

**Comment by joshzcold** [comment]
Maybe I can go double check if the "new game" page is outputting correct format. 
@ItzEarthy you could try editing a json file like Noah did to brute force it before Christmas

**Comment by ItzEarthy** [comment]
I originally downloaded the .json file from GitHub and then edited it with the changed questions and then renamed the file. Not sure what id have to change regarding the file. when I upload the original file I downloaded, it also doesn't work. I've been using the system for years now and this is the first time I've tried doing a custom version.

**Comment by NoahTheBaguette** [comment]
I kept it as the same name try doing that

**Comment by ItzEarthy** [comment]
It is exactly the same name

**Comment by ItzEarthy** [comment]
> any browser console logs to indicate what the problem is?

@joshzcold here is the console output error
![image](https://github.com/user-attachments/assets/bc45f9c9-7cdc-43fa-a41a-2e94d0add4aa)

**Comment by NoahTheBaguette** [comment]
Maybe try downloading a json from the folder and upload that one and just
see if it works.

**Comment by ItzEarthy** [comment]
I figured it out 🤦

**Comment by joshzcold** [comment]
Sweet great to hear 👍

I was really worried there was some obscure bug depending on browser version or OS that was causing it 😅
