### ISSUE TITLE
Cannot upload CSV on firefox

### ISSUE THREAD

**Issue by syntax53** [joshzcold/Cold-Family-Feud#93]
Error when uploading CSV file to your site: Unknown file type in game load

When I look in the debug, I see it's detecting my file as excel:

![image](https://github.com/user-attachments/assets/186475d3-4d4d-4ea2-8e9e-b299774edaf4)

Even when I open a fresh notepad++ file, paste in the text, and save it as a TXT and then rename it to CSV, it still says that.  I also took a file I created a couple weeks ago as a test that worked then and it's doing the same thing.

**Comment by joshzcold** [comment]
Hey @syntax53 can you attach your game file so I can take a look?

**Comment by joshzcold** [comment]
My hunch is that you need to save it in a special way in Microsoft office for it to be a "true" CSV file, but I can check it's contents to see what's up

**Comment by syntax53** [comment]
So... it works in Chrome but not in Firefox.
[famfxmas2024.csv](https://github.com/user-attachments/files/18236983/famfxmas2024.csv)

**Comment by joshzcold** [comment]
I do parse it into the expect format on the client. 

But the fact that this only happens on Firefox gives me a hint that I can start looking up.

**Comment by joshzcold** [comment]
https://support.mozilla.org/en-US/questions/1401889

**Comment by syntax53** [comment]
Fair.  Is it really necessary to very the mime type though?  Just check that it ends in .csv and then check if it can read in the expected format?
